# Generated by Django 4.2.11 on 2024-04-07 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Срочно пора заняться'), (1, 'Сразу после важных дел'), (2, 'Пора бы начать'), (3, 'Когда-нибудь потом'), (4, 'В другой жизни')], default=4, verbose_name='Приоритет')),
                ('time_required', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Примерное время на задачу (в часах)')),
                ('progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.category', verbose_name='Категория')),
            ],
        ),
    ]
