# Generated by Django 4.2.11 on 2024-04-08 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_options_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='progress',
        ),
        migrations.AlterField(
            model_name='plan',
            name='time_required',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Примерное время на задачу (в часах)'),
        ),
    ]
