# Generated by Django 4.2.11 on 2024-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_priority_alter_plan_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Приоритет'),
        ),
    ]
