# Generated by Django 4.2.11 on 2024-04-12 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_remove_category_description_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дедлайн'),
            preserve_default=False,
        ),
    ]
