# Generated by Django 4.2.11 on 2024-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_plan_created_at_plan_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('created_at',), 'verbose_name': 'план', 'verbose_name_plural': 'Планы'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
    ]
