# Generated by Django 4.2.11 on 2024-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_plan_options_alter_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='Дедлайн'),
        ),
    ]
