# Generated by Django 4.2.11 on 2024-04-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_alter_plan_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
