# Generated by Django 4.2.11 on 2024-04-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_alter_plan_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ('priority',), 'verbose_name': 'приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
    ]
