# Generated by Django 4.2.11 on 2024-04-12 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_alter_priority_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='progress',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс'),
        ),
        migrations.AddField(
            model_name='plan',
            name='task_now',
            field=models.BooleanField(default=False, verbose_name='Сейчас задача'),
        ),
    ]
