# Generated by Django 4.2.11 on 2024-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_plan_progress_plan_task_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='task_now',
            new_name='is_task',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='Задача закончена'),
        ),
    ]
